In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlibinline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

UsageError: Line magic function `%matplotlibinline` not found.


In [36]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

EXAMPLE 1

In [37]:
# aligning into steps inside tupe
steps = [("standard_scaler",StandardScaler()),
         ("classifier",LogisticRegression())]
# steps
Pipeline(steps)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [38]:
pipe = Pipeline(steps)
pipe


Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [39]:
# tp visualize this pipeline
from sklearn import set_config
set_config(display="diagram")
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [40]:
#creating a dataset
from sklearn.datasets import make_classification
X,y = make_classification(n_samples = 1000)
X.shape
y.shape

(1000,)

In [58]:
# creating a dataframe
df = pd.DataFrame(X,columns=[f"Feature_{i}" for i in range(X.shape[1])])
df["Target"] = y
df.head()

Feature_0  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  \
0   0.597038  -1.352813  -1.402277   0.350563   0.003674  -0.417495   
1  -0.115978   0.053798   0.797684   0.219871   2.438695   0.080165   
2   1.040451   0.629863   0.798772  -0.186918   0.845329   0.694298   
3   0.210652   1.228047   1.420101  -0.574391   0.653776  -0.142063   
4  -0.238904  -0.373032   1.173637  -0.932680  -0.976331   0.048838   

   Feature_6  Feature_7  Feature_8  Feature_9  ...  Feature_11  Feature_12  \
0  -0.577987  -1.368140   0.670038  -0.845990  ...    0.020210   -2.168257   
1   0.261530   1.590006   0.519804   1.035703  ...    1.443394    0.448503   
2  -0.109358   0.986270   1.416247   0.823294  ...   -1.815757   -0.292363   
3  -0.804006   1.276159   0.756894   0.768178  ...    0.413036    1.125874   
4   0.421633  -1.035067   0.665975  -0.700471  ...    0.850785   -2.055922   

   Feature_13  Feature_14  Feature_15  Feature_16  Feature_17  Feature_18  \
0    1.407978    0.113647    1.146303    1.003268   -1.239765    0.278408   
1    0.182129   -0.491836   -1.177804   -0.301878    2.988346    0.813020   
2   -0.114234   -2.003860   -0.198949    0.011953   -0.524617    0.998218   
3    1.190503   -1.334654   -1.130779    0.619619   -0.081976   -0.060938   
4   -0.930151    0.761982    0.689577   -0.803396   -0.734873    1.620186   

   Feature_19  Target  
0   -0.991992       0  
1    0.757276       1  
2   -0.892433       0  
3    1.082984       1  
4   -0.295291       0  

[5 rows x 21 columns]

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 42)

In [42]:
# fitting X_train,y_train inside the pipe
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [43]:
y_pred = pipe.predict(X_test)
y_pred
# y_pred_pro = [1 if i>=0.5 else 0 for i in y_pred]
# y_pred_pro

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,

In [45]:
import warnings
warnings.filterwarnings("ignore")

EXAMPLE 2

In [44]:
# implementing pipleline with a StandardScaler, dimensionality reduction and then estimators
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [50]:
ex_steps = [('standardscaler',StandardScaler()),('pca',PCA(n_components=3)),('svc',SVC())]
ex_steps

[('standardscaler', StandardScaler()),
 ('pca', PCA(n_components=3)),
 ('svc', SVC())]

In [52]:
ex_pipe = Pipeline(ex_steps)
ex_pipe

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('pca', PCA(n_components=3)), ('svc', SVC())])

In [53]:
ex_pipe.fit(X_train,y_train)
y_pred2 = ex_pipe.predict(X_test)
y_pred2

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [62]:
# To view what are the n_components it has taken
pca_components = ex_pipe["pca"].components_
pca_components
# pca_components.shape

array([[ 0.05540458, -0.0117504 , -0.06295133, -0.06212462,  0.09084163,
        -0.02226103,  0.0450957 ,  0.60299509, -0.0791742 ,  0.55994823,
         0.01601456, -0.053984  ,  0.0607077 ,  0.02046375,  0.03327792,
        -0.52035425, -0.04701438,  0.0877374 ,  0.0122512 ,  0.0746036 ],
       [ 0.14830692,  0.05690088,  0.05579482, -0.04034981, -0.01403522,
        -0.04048029, -0.01369543, -0.15395499, -0.00474761, -0.32079726,
        -0.02336177,  0.05515956, -0.17958952,  0.04347089, -0.10859217,
        -0.41410804,  0.06545453,  0.15618846,  0.00169041,  0.76920558],
       [-0.00116358, -0.29426877,  0.20162144, -0.01957737,  0.436311  ,
         0.4647378 ,  0.10327101, -0.02776525, -0.06868779, -0.02757515,
         0.0254833 ,  0.30351118,  0.0741621 ,  0.53532892,  0.15167186,
         0.0184483 , -0.00913713,  0.08472559, -0.18339819,  0.00450801]])

In [63]:
pca_component = ex_pipe.named_steps["pca"].components_
pca_component

array([[ 0.05540458, -0.0117504 , -0.06295133, -0.06212462,  0.09084163,
        -0.02226103,  0.0450957 ,  0.60299509, -0.0791742 ,  0.55994823,
         0.01601456, -0.053984  ,  0.0607077 ,  0.02046375,  0.03327792,
        -0.52035425, -0.04701438,  0.0877374 ,  0.0122512 ,  0.0746036 ],
       [ 0.14830692,  0.05690088,  0.05579482, -0.04034981, -0.01403522,
        -0.04048029, -0.01369543, -0.15395499, -0.00474761, -0.32079726,
        -0.02336177,  0.05515956, -0.17958952,  0.04347089, -0.10859217,
        -0.41410804,  0.06545453,  0.15618846,  0.00169041,  0.76920558],
       [-0.00116358, -0.29426877,  0.20162144, -0.01957737,  0.436311  ,
         0.4647378 ,  0.10327101, -0.02776525, -0.06868779, -0.02757515,
         0.0254833 ,  0.30351118,  0.0741621 ,  0.53532892,  0.15167186,
         0.0184483 , -0.00913713,  0.08472559, -0.18339819,  0.00450801]])

Complex examples for column transformer

In [68]:
# pipeline 1 for numerical features
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [72]:
# pipeline 1 for numerical columns
numerical_processor = Pipeline(steps = [('numerical_imputer',SimpleImputer(missing_values=np.nan,strategy = "mean")),
                                        ('standatardscaler',StandardScaler())])
numerical_processor

Pipeline(steps=[('numerical_imputer', SimpleImputer()),
                ('standatardscaler', StandardScaler())])

In [77]:
#pipeline 2 for categorical columns
categorical_processor = Pipeline(steps = [('categorical_imputer',SimpleImputer(fill_value="missing", strategy = "constant")),
                                         ('onehot',OneHotEncoder(handle_unknown = "ignore"))])
categorical_processor

Pipeline(steps=[('categorical_imputer',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [80]:
# combining both pipeline using columntransformer
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer([('Categorical',categorical_processor,["gender","city"]),('Numerical',numerical_processor,["age","Height","weight"])])
preprocessor

ColumnTransformer(transformers=[('Categorical',
                                 Pipeline(steps=[('categorical_imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('Numerical',
                                 Pipeline(steps=[('numerical_imputer',
                                                  SimpleImputer()),
                                                 ('standatardscaler',
                                                  StandardScaler())]),
                                 ['age', 'Height', 'weight'])])

In [82]:
# add an estimator(algorithm)
from sklearn.pipeline import make_pipeline
#make_pipeline(need to customize the pipleline)
final_pipe = make_pipeline(preprocessor, LogisticRegression())
final_pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('Categorical',
                                                  Pipeline(steps=[('categorical_imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('Numerical',
                                                  Pipeline(steps=[('numerical_imputer',
                                                                   SimpleImputer()),
                                                                  ('standatardscaler',
                                                                   StandardScaler())]),
                                                  ['age', 'Height',
                                                   'weight'])])),
                ('logisticregression', LogisticRegression())])

In [ ]:
#sales need to predict,price, promotions, categorical variables (8 seasons) 
y = m*x + c

Total sales =  m * price + m * promotions + m * season1 + m * season2 + m * season3 + 

In [ ]:
season1, season2, 

In [ ]:
mean absolute percentage error = i=1 to n |actual value - predicted value| * 100/actual value

In [5]:
# code to caluclate mape
actual = [1,5,6,8,10]
predicted = [4,6,8,8,10]
sum = 0
for i,j in zip(actual,predicted):
    sum = sum + (i-j)
print((sum/len(actual)) * 100)

-120.0


In [ ]:
# 0 is failure


In [4]:
# return the prime numbers between or in the given range
def fun(num1,num2):
    li = []
    a = max(num1,num2)
    for i in range(num1,num2):
        if i > 1:
            for j in range(2,a):
                if i%j==0:
                    break
                else:
                    li.append(i)
    return li
num1,num2 = map(int,input().split())
print(fun(num1,num2))

1 10
[3, 5, 5, 5, 7, 7, 7, 7, 7, 9]
